apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: topology-aware-model-cache
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: shared-vast
