apiVersion: v1
kind: ServiceAccount
metadata:
  name: glm-5-2
  namespace: nilig-agentx-slo
  labels:
    llm-d.ai/accelerator-variant: gpu
    llm-d.ai/accelerator-vendor: nvidia
    llm-d.ai/benchmark: p2p-cache-routing-glm
    llm-d.ai/model: GLM-5.2-FP8
imagePullSecrets:
- name: niliguy-quay-pull
