apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: vllm-openai-g-a6a03f4d-oss-120b
  namespace: nilig-topology-aware
  labels:
spec:
  selector:
    matchLabels:
      llm-d.ai/inferenceServing: "true"
      llm-d.ai/model: openai-g-a6a03f4d-oss-120b
  podMetricsEndpoints:
  - port: metrics
    path: /metrics
    interval: 30s
