apiVersion: v1
data:
  latest: 'analyze: true

    endpoint_url: http://10.16.3.183

    experiment_ids:

    - inference-perf-1787589587-closvy

    harness: inference-perf

    hostname: Nilis-MacBook-Pro.local

    model: openai/gpt-oss-120b

    namespace: nilig-topology-aware

    output: local

    parallelism: 1

    pvc_name: workload-pvc

    pvc_results_paths:

    - /requests/inference-perf-1787589587-closvy_1

    pvc_results_prefix: /requests

    timestamp: 20260824T164325Z

    user: niliguy

    workload: guide_pd-disaggregation_2.yaml

    '
  run-20260824T164325Z: 'analyze: true

    endpoint_url: http://10.16.3.183

    experiment_ids:

    - inference-perf-1787589587-closvy

    harness: inference-perf

    hostname: Nilis-MacBook-Pro.local

    model: openai/gpt-oss-120b

    namespace: nilig-topology-aware

    output: local

    parallelism: 1

    pvc_name: workload-pvc

    pvc_results_paths:

    - /requests/inference-perf-1787589587-closvy_1

    pvc_results_prefix: /requests

    timestamp: 20260824T164325Z

    user: niliguy

    workload: guide_pd-disaggregation_2.yaml

    '
kind: ConfigMap
metadata:
  name: llm-d-benchmark-run-parameters
  namespace: nilig-topology-aware
